    .hword 28, 4096
    .word Ch11EphraimTileAnimations_frame_0
    .hword 28, 4096
    .word Ch11EphraimTileAnimations_frame_1
    .hword 28, 4096
    .word Ch11EphraimTileAnimations_frame_2
    .hword 28, 4096
    .word Ch11EphraimTileAnimations_frame_3
    .hword 28, 4096
    .word Ch11EphraimTileAnimations_frame_4
    .hword 28, 4096
    .word Ch11EphraimTileAnimations_frame_5
    .hword 28, 4096
    .word Ch11EphraimTileAnimations_frame_6
    .hword 28, 4096
    .word Ch11EphraimTileAnimations_frame_7
    .word 0, 0
