    .hword 28, 4096
    .word TileAnimations2_frame_0
    .hword 28, 4096
    .word TileAnimations2_frame_1
    .hword 28, 4096
    .word TileAnimations2_frame_2
    .hword 28, 4096
    .word TileAnimations2_frame_3
    .hword 28, 4096
    .word TileAnimations2_frame_4
    .hword 28, 4096
    .word TileAnimations2_frame_5
    .hword 28, 4096
    .word TileAnimations2_frame_6
    .hword 28, 4096
    .word TileAnimations2_frame_7
    .hword 28, 4096
    .word TileAnimations2_frame_8
    .hword 28, 4096
    .word TileAnimations2_frame_9
    .hword 28, 4096
    .word TileAnimations2_frame_10
    .hword 28, 4096
    .word TileAnimations2_frame_11
    .hword 28, 4096
    .word TileAnimations2_frame_12
    .hword 28, 4096
    .word TileAnimations2_frame_13
    .hword 28, 4096
    .word TileAnimations2_frame_14
    .hword 28, 4096
    .word TileAnimations2_frame_15
    .word 0, 0
