    .hword 28, 4096
    .word TileAnimationsUnused1_frame_0
    .hword 28, 4096
    .word TileAnimationsUnused1_frame_1
    .hword 28, 4096
    .word TileAnimationsUnused1_frame_2
    .hword 28, 4096
    .word TileAnimationsUnused1_frame_3
    .hword 28, 4096
    .word TileAnimationsUnused1_frame_4
    .hword 28, 4096
    .word TileAnimationsUnused1_frame_5
    .hword 28, 4096
    .word TileAnimationsUnused1_frame_6
    .hword 28, 4096
    .word TileAnimationsUnused1_frame_7
    .hword 28, 4096
    .word TileAnimationsUnused1_frame_8
    .hword 28, 4096
    .word TileAnimationsUnused1_frame_9
    .hword 28, 4096
    .word TileAnimationsUnused1_frame_10
    .hword 28, 4096
    .word TileAnimationsUnused1_frame_11
    .hword 28, 4096
    .word TileAnimationsUnused1_frame_12
    .hword 28, 4096
    .word TileAnimationsUnused1_frame_13
    .hword 28, 4096
    .word TileAnimationsUnused1_frame_14
    .hword 28, 4096
    .word TileAnimationsUnused1_frame_15
    .word 0, 0
