    .hword 11, 1280
    .word TileAnimationsUnused2_frame_0
    .hword 11, 1280
    .word TileAnimationsUnused2_frame_1
    .hword 11, 1280
    .word TileAnimationsUnused2_frame_2
    .hword 11, 1280
    .word TileAnimationsUnused2_frame_3
    .hword 11, 1280
    .word TileAnimationsUnused2_frame_4
    .hword 11, 1280
    .word TileAnimationsUnused2_frame_5
    .hword 11, 1280
    .word TileAnimationsUnused2_frame_6
    .hword 11, 1280
    .word TileAnimationsUnused2_frame_7
    .word 0, 0
