    .word TileAnimations4_frame_0
    .byte 19, 4, 60, 0
    .word TileAnimations4_frame_1
    .byte 18, 4, 60, 0
    .word TileAnimations4_frame_2
    .byte 17, 4, 60, 0
    .word TileAnimations4_frame_3
    .byte 16, 4, 60, 0
    .word TileAnimations4_frame_4
    .byte 16, 4, 60, 0
    .word TileAnimations4_frame_5
    .byte 16, 4, 60, 0
    .word TileAnimations4_frame_6
    .byte 17, 4, 60, 0
    .word TileAnimations4_frame_7
    .byte 18, 4, 60, 0
    .word TileAnimations4_frame_8
    .byte 19, 4, 60, 0
    .word TileAnimations4_frame_9
    .byte 18, 4, 60, 0
    .word TileAnimations4_frame_10
    .byte 17, 4, 60, 0
    .word TileAnimations4_frame_11
    .byte 16, 4, 60, 0
    .word TileAnimations4_frame_12
    .byte 16, 4, 60, 0
    .word TileAnimations4_frame_13
    .byte 17, 4, 60, 0
    .word TileAnimations4_frame_14
    .byte 18, 4, 60, 0
    .word 0, 0
