    .word TileAnimationsUnused4_frame_0
    .byte 5, 3, 49, 0
    .word TileAnimationsUnused4_frame_1
    .byte 6, 3, 49, 0
    .word TileAnimationsUnused4_frame_2
    .byte 6, 3, 49, 0
    .word TileAnimationsUnused4_frame_3
    .byte 8, 3, 49, 0
    .word TileAnimationsUnused4_frame_4
    .byte 6, 3, 49, 0
    .word TileAnimationsUnused4_frame_5
    .byte 6, 3, 49, 0
    .word TileAnimationsUnused4_frame_6
    .byte 7, 3, 49, 0
    .word TileAnimationsUnused4_frame_7
    .byte 9, 3, 49, 0
    .word TileAnimationsUnused4_frame_8
    .byte 7, 3, 49, 0
    .word TileAnimationsUnused4_frame_9
    .byte 8, 3, 49, 0
    .word TileAnimationsUnused4_frame_10
    .byte 8, 3, 49, 0
    .word TileAnimationsUnused4_frame_11
    .byte 8, 3, 49, 0
    .word TileAnimationsUnused4_frame_0
    .byte 4, 3, 49, 0
    .word TileAnimationsUnused4_frame_1
    .byte 7, 3, 49, 0
    .word 0, 0
