    .word TileAnimationsUnused3_frame_0
    .byte 61, 4, 60, 0
    .word TileAnimationsUnused3_frame_0
    .byte 61, 4, 60, 0
    .word TileAnimationsUnused3_frame_2
    .byte 3, 4, 60, 0
    .word TileAnimationsUnused3_frame_3
    .byte 4, 4, 60, 0
    .word TileAnimationsUnused3_frame_4
    .byte 5, 4, 60, 0
    .word TileAnimationsUnused3_frame_5
    .byte 4, 4, 60, 0
    .word TileAnimationsUnused3_frame_6
    .byte 3, 4, 60, 0
    .word TileAnimationsUnused3_frame_7
    .byte 2, 4, 60, 0
    .word 0, 0
