#ifndef GUARD_CONSTANTS_CLASSES_H
#define GUARD_CONSTANTS_CLASSES_H

enum {
    CLASS_NONE                = 0x00,

    CLASS_EPHRAIM_LORD        = 0x01,
    CLASS_EIRIKA_LORD         = 0x02,
    CLASS_EPHRAIM_MASTER_LORD = 0x03,
    CLASS_EIRIKA_MASTER_LORD  = 0x04,
    CLASS_CAVALIER            = 0x05,
    CLASS_CAVALIER_F          = 0x06,
    CLASS_PALADIN             = 0x07,
    CLASS_PALADIN_F           = 0x08,
    CLASS_ARMOR_KNIGHT        = 0x09,
    CLASS_ARMOR_KNIGHT_F      = 0x0A,
    CLASS_GENERAL             = 0x0B,
    CLASS_GENERAL_F           = 0x0C,
    CLASS_THIEF               = 0x0D,
    CLASS_MANAKETE            = 0x0E, // TODO: which one?
    CLASS_MERCENARY           = 0x0F,
    CLASS_MERCENARY_F         = 0x10,
    CLASS_HERO                = 0x11,
    CLASS_HERO_F              = 0x12,
    CLASS_MYRMIDON            = 0x13,
    CLASS_MYRMIDON_F          = 0x14,
    CLASS_SWORDMASTER         = 0x15,
    CLASS_SWORDMASTER_F       = 0x16,
    CLASS_ASSASSIN            = 0x17,
    CLASS_ASSASSIN_F          = 0x18,
    CLASS_ARCHER              = 0x19,
    CLASS_ARCHER_F            = 0x1A,
    CLASS_SNIPER              = 0x1B,
    CLASS_SNIPER_F            = 0x1C,
    CLASS_RANGER              = 0x1D,
    CLASS_RANGER_F            = 0x1E,
    CLASS_WYVERN_RIDER        = 0x1F,
    CLASS_WYVERN_RIDER_F      = 0x20,
    CLASS_WYVERN_LORD         = 0x21,
    CLASS_WYVERN_LORD_F       = 0x22,
    CLASS_WYVERN_KNIGHT       = 0x23,
    CLASS_WYVERN_KNIGHT_F     = 0x24,
    CLASS_MAGE                = 0x25,
    CLASS_MAGE_F              = 0x26,
    CLASS_SAGE                = 0x27,
    CLASS_SAGE_F              = 0x28,
    CLASS_MAGE_KNIGHT         = 0x29,
    CLASS_MAGE_KNIGHT_F       = 0x2A,
    CLASS_BISHOP              = 0x2B,
    CLASS_BISHOP_F            = 0x2C,
    CLASS_SHAMAN              = 0x2D,
    CLASS_SHAMAN_F            = 0x2E,
    CLASS_DRUID               = 0x2F,
    CLASS_DRUID_F             = 0x30,
    CLASS_SUMMONER            = 0x31,
    CLASS_SUMMONER_F          = 0x32,
    CLASS_ROGUE               = 0x33,
    CLASS_GORGONEGG2          = 0x34,
    CLASS_GREAT_KNIGHT        = 0x35,
    CLASS_GREAT_KNIGHT_F      = 0x36,
    CLASS_RECRUIT_T1          = 0x37,
    CLASS_JOURNEYMAN_T2       = 0x38,
    CLASS_PUPIL_T2            = 0x39,
    CLASS_RECRUIT_T2          = 0x3A,
    CLASS_MANAKETE_2          = 0x3B, // TODO: which one?
    CLASS_MANAKETE_MYRRH      = 0x3C,
    CLASS_JOURNEYMAN          = 0x3D,
    CLASS_PUPIL               = 0x3E,
    CLASS_FIGHTER             = 0x3F,
    CLASS_WARRIOR             = 0x40,
    CLASS_BRIGAND             = 0x41,
    CLASS_PIRATE              = 0x42,
    CLASS_BERSERKER           = 0x43,
    CLASS_MONK                = 0x44,
    CLASS_PRIEST              = 0x45,
    CLASS_BARD                = 0x46,
    CLASS_RECRUIT             = 0x47,
    CLASS_PEGASUS_KNIGHT      = 0x48,
    CLASS_FALCON_KNIGHT       = 0x49,
    CLASS_CLERIC              = 0x4A,
    CLASS_TROUBADOUR          = 0x4B,
    CLASS_VALKYRIE            = 0x4C,
    CLASS_DANCER              = 0x4D,
    CLASS_SOLDIER             = 0x4E,
    CLASS_NECROMANCER         = 0x4F,
    CLASS_FLEET               = 0x50,
    CLASS_PHANTOM             = 0x51,
    CLASS_REVENANT            = 0x52,
    CLASS_ENTOUMBED           = 0x53,
    CLASS_BONEWALKER          = 0x54,
    CLASS_BONEWALKER_BOW      = 0x55,
    CLASS_WIGHT               = 0x56,
    CLASS_WIGHT_BOW           = 0x57,
    CLASS_BAEL                = 0x58,
    CLASS_ELDER_BAEL          = 0x59,
    CLASS_CYCLOPS             = 0x5A,
    CLASS_MAUTHEDOOG          = 0x5B,
    CLASS_GWYLLGI             = 0x5C,
    CLASS_TARVOS              = 0x5D,
    CLASS_MAELDUIN            = 0x5E,
    CLASS_MOGALL              = 0x5F,
    CLASS_ARCH_MOGALL         = 0x60,
    CLASS_GORGON              = 0x61,
    CLASS_GORGONEGG           = 0x62,
    CLASS_GARGOYLE            = 0x63,
    CLASS_DEATHGOYLE          = 0x64,
    CLASS_DRACO_ZOMBIE        = 0x65,
    CLASS_DEMON_KING          = 0x66,
    CLASS_BLST_REGULAR_USED   = 0x67,
    CLASS_BLST_LONG_USED      = 0x68,
    CLASS_BLST_KILLER_USED    = 0x69,
    CLASS_BLST_REGULAR_EMPTY  = 0x6A,
    CLASS_BLST_LONG_EMPTY     = 0x6B,
    CLASS_BLST_KILLER_EMPTY   = 0x6C,
    CLASS_CIVILIAN_M1         = 0x6D,
    CLASS_CIVILIAN_F1         = 0x6E,
    CLASS_CIVILIAN_M2         = 0x6F,
    CLASS_CIVILIAN_F2         = 0x70,
    CLASS_CIVILIAN_M3         = 0x71,
    CLASS_CIVILIAN_F3         = 0x72,
    CLASS_PEER                = 0x73,
    CLASS_QUEEN               = 0x74,
    CLASS_PRINCE              = 0x75,
    CLASS_QUEEN_2             = 0x76,
    CLASS_UNK77               = 0x77, // TODO: figure out
    CLASS_FALLEN_PRINCE       = 0x78,
    CLASS_TENT                = 0x79,
    CLASS_PONTIFEX            = 0x7A,
    CLASS_FALLEN_PEER         = 0x7B,
    CLASS_CYCLOPS_2           = 0x7C,
    CLASS_ELDER_BAEL_2        = 0x7D,
    CLASS_JOURNEYMAN_T1       = 0x7E,
    CLASS_PUPIL_T1            = 0x7F,

    // Camp/Tent structures (id_space "class" domain, widened past 0x7F --
    // see docs/id_space.md and include/bmsave.h). Like CLASS_OBSTACLE below,
    // these are only ever assigned to a transient, non-persisted fake battle
    // unit (see src/bmbattle.c), never to a real deployed roster Unit, in
    // any build configuration.
    CLASS_CAMP                = 0x80,
    CLASS_TENT_STRUCTURE      = 0x81,

    // New classes (2026-09 FE-Repo pack import) -- appended after the
    // last vanilla+expansion slot above; must match their position in
    // src/data/classes.json's array exactly (classId == array index + 1,
    // see src/unit_icon_move_data.c/gMuInfoTable's own comment on this).
    CLASS_LYN_LORD            = 0x82,
    CLASS_NOMAD               = 0x83,
    CLASS_NOMAD_F             = 0x84,
    CLASS_NOMAD_TROOPER       = 0x85,
    CLASS_NOMAD_TROOPER_F     = 0x86,

    // Batch2 custom classes (2026-09 import).
    CLASS_SWASHBUCKLER_F         = 0x87,
    CLASS_SWASHBUCKLER           = 0x88,
    CLASS_LEO_BERSERKER          = 0x89,
    CLASS_GRAND_MAHOUT           = 0x8A,
    CLASS_ARCANIST_NURAMON       = 0x8B,
    CLASS_HALBERDIER_CUSTOM      = 0x8C,
    CLASS_MIKO                   = 0x8D,
    CLASS_WAR_CLERIC             = 0x8E,
    CLASS_WITCH                  = 0x8F,
    CLASS_ANGEL                  = 0x90,
    CLASS_BRIGHID                = 0x91,
    CLASS_ARCANIST_DEVISIAN      = 0x92,
    CLASS_MAGICIAN               = 0x93,
    CLASS_OCCULTIST              = 0x94,
    CLASS_BLADER_F               = 0x95,
    CLASS_HARBINGER              = 0x96,
    CLASS_EXECUTIONER            = 0x97,
    CLASS_HEAVY_INFANTRY         = 0x98,
    CLASS_BARON_CUSTOM           = 0x99,
    CLASS_SHIELD_GENERAL         = 0x9A,
    CLASS_BLACK_DRAGON           = 0x9B,
    CLASS_DJINN                  = 0x9C,
    CLASS_LIVING_ARMOR           = 0x9D,
    CLASS_FELLBEAST              = 0x9E,
    CLASS_SAMURAI_F              = 0x9F,
    CLASS_MASTER_NINJA           = 0xA0,
    CLASS_HOODED_NINJA           = 0xA1,
    CLASS_MYRMIDON_FE15_F        = 0xA2,
    CLASS_MYRMIDON_FE15          = 0xA3,
    CLASS_KATARINA_FENCER        = 0xA4,
    CLASS_THUG                   = 0xA5,
    CLASS_DREAD_FIGHTER          = 0xA6,
    CLASS_FIR_SWORDMASTER        = 0xA7,
    CLASS_TRUEBLADE              = 0xA8,
    CLASS_RED_MAGE               = 0xA9,
    CLASS_MOLOCH                 = 0xAA,
    CLASS_TACTICIAN_CUSTOM       = 0xAB,
    CLASS_TRICKSTER_F            = 0xAC,
    CLASS_TRICKSTER              = 0xAD,
    CLASS_VILLAGER_F             = 0xAE,
    CLASS_VILLAGER               = 0xAF,
    CLASS_LEGION_KING            = 0xB0,
    CLASS_ONI_CHIEFTAIN          = 0xB1,
    CLASS_ELFFIN_FANCY           = 0xB2,
    CLASS_MOUNTED_MARAUDER       = 0xB3,
    CLASS_MECHANIST              = 0xB4,
    CLASS_DRAGOON_CUSTOM         = 0xB5,
    CLASS_LANCER_CUSTOM          = 0xB6,
    CLASS_MILITIA                = 0xB7,
    CLASS_SENTINEL               = 0xB8,
    CLASS_T1_LANCER              = 0xB9,
    CLASS_GLADIATOR              = 0xBA,
    CLASS_HORN_BRIGAND           = 0xBB,
    CLASS_HORN_SOLDIER           = 0xBC,
    CLASS_HUNTER                 = 0xBD,
    CLASS_SUPPLIER_ANNA          = 0xBE,
    CLASS_SANDWORM               = 0xBF,
    CLASS_CURSED_SWORD           = 0xC0,
    CLASS_MAGICAL_TOMES          = 0xC1,
    CLASS_MIMIC_CHEST            = 0xC2,
    CLASS_MOSQUITO               = 0xC3,
    CLASS_PHANTOM_CUSTOM         = 0xC4,
    CLASS_SLIME                  = 0xC5,
    CLASS_WARBIRD                = 0xC6,
    CLASS_ADVENTURER             = 0xC7,
    CLASS_LYN_GREAT_LORD         = 0xC8,
    CLASS_ELDER                  = 0xC9,
    CLASS_ARBALEST               = 0xCA,
    CLASS_ARBALEST_F             = 0xCB,
    CLASS_FELLBEAST_KNIGHT       = 0xCC,
    CLASS_GRIFFON                = 0xCD,
    CLASS_ARCHSAGE               = 0xCE,
    CLASS_MALIG_QUEEN            = 0xCF,
    CLASS_SERAPH_KNIGHT          = 0xD0,

    // Hiding the game's misery
    CLASS_OBSTACLE = CLASS_EPHRAIM_LORD,
};

#endif // GUARD_CONSTANTS_CLASSES_H
