#ifndef GUARD_CONSTANTS_FACES_H
#define GUARD_CONSTANTS_FACES_H

enum {
    FID_EIRIKA              = 0x02,

    FID_LUTE                = 0x10,

    FID_EPHRAIM             = 0x14,

    FID_AMELIA              = 0x19,
    FID_EWAN                = 0x21,
    FID_DOZLA               = 0x23,
    FID_MYRRH               = 0x26,

    FID_ANNA                = 0x64,
    FID_SHOP_ARMORY         = 0x65,
    FID_SHOP_VENDOR         = 0x66,
    FID_ARENA               = 0x67,
    FID_SHOP_SECRET         = 0x68,

    FID_SUPPLY              = 0xAB,

    // Generic class-card/default portrait IDs used by class data.
    FID_CLASS_EIRIKA                 = 0x01,
    FID_CLASS_VILLAGER_MAN_2         = 0x59,
    FID_CLASS_VILLAGER_YOUNG_MAN     = 0x5C,
    FID_CLASS_VILLAGER_OLD_WOMAN     = 0x5E,
    FID_CLASS_VILLAGER_GIRL_BLACK_HAIR = 0x61,
    FID_CLASS_VILLAGER_GIRL_YOUNG    = 0x62,
    FID_CLASS_ANNA                   = 0x63,
    FID_CLASS_SWORDMASTER            = 0x72,
    FID_CLASS_FIGHTER                = 0x73,
    FID_CLASS_WARRIOR                = 0x74,
    FID_CLASS_KNIGHT                 = 0x75,
    FID_CLASS_GENERAL                = 0x76,
    FID_CLASS_ARCHER                 = 0x77,
    FID_CLASS_SNIPER                 = 0x78,
    FID_CLASS_PRIEST                 = 0x79,
    FID_CLASS_BISHOP                 = 0x7A,
    FID_CLASS_MAGE                   = 0x7B,
    FID_CLASS_SAGE                   = 0x7C,
    FID_CLASS_SHAMAN                 = 0x7D,
    FID_CLASS_DRUID                  = 0x7E,
    FID_CLASS_CAVALIER               = 0x7F,
    FID_CLASS_PALADIN                = 0x80,
    FID_CLASS_TROUBADOUR             = 0x81,
    FID_CLASS_VALKYRIE               = 0x82,
    FID_CLASS_NOMAD                  = 0x83,
    FID_CLASS_FALCON_KNIGHT          = 0x86,
    FID_CLASS_WYVERN_RIDER           = 0x87,
    FID_CLASS_WYVERN_LORD            = 0x88,
    FID_CLASS_SOLDIER                = 0x89,
    FID_CLASS_BANDIT                 = 0x8A,
    FID_CLASS_PIRATE                 = 0x8B,
    FID_CLASS_BERSERKER              = 0x8C,
    FID_CLASS_THIEF                  = 0x8D,
    FID_CLASS_MANAKETE               = 0x8E,
    FID_CLASS_MERCENARY              = 0x8F,
    FID_CLASS_HERO                   = 0x90,
    FID_CLASS_FLEET                  = 0x91,
    FID_CLASS_WYVERN_KNIGHT          = 0x92,
    FID_CLASS_ROGUE                  = 0x93,
    FID_CLASS_MAGE_KNIGHT            = 0x94,
    FID_CLASS_GREAT_KNIGHT           = 0x95,
    FID_CLASS_RANGER                 = 0x96,
    FID_CLASS_PHANTOM                = 0x97,
    FID_CLASS_REVENANT               = 0x98,
    FID_CLASS_ENTOMBED               = 0x99,
    FID_CLASS_BONEWALKER             = 0x9A,
    FID_CLASS_WIGHT                  = 0x9B,
    FID_CLASS_BAEL                   = 0x9C,
    FID_CLASS_ELDER_BAEL             = 0x9D,
    FID_CLASS_CYCLOPS                = 0x9E,
    FID_CLASS_MAUTHEDOOG             = 0x9F,
    FID_CLASS_GWYLLGI                = 0xA0,
    FID_CLASS_TARVOS                 = 0xA1,
    FID_CLASS_MAELDUIN               = 0xA2,
    FID_CLASS_MOGALL                 = 0xA3,
    FID_CLASS_ARCH_MOGALL            = 0xA4,
    FID_CLASS_GORGON                 = 0xA5,
    FID_CLASS_GARGOYLE               = 0xA6,
    FID_CLASS_DEATHGOYLE             = 0xA7,
    FID_CLASS_MANAKETE_ZOMBIE        = 0xA8,
    FID_CLASS_DEMON_KING             = 0xA9,
    FID_CLASS_MYSTERY_FADED          = 0xAA,

    FID_FACTION_CHIBI       = 0x7F00,
    FID_WAKWI              = 0x02,
    FID_ISHKODE              = 0x04,
    FID_FREDERICK              = 0x05,
    FID_FOX              = 0x06,
    FID_ASIN              = 0x07,
    FID_LIZ              = 0x08,
    FID_TOREN              = 0x09,
    FID_LENORA             = 0x0A,
    FID_VOLIK              = 0x0C,
    FID_CLARISSE           = 0x0E,
    FID_ELAYNE             = 0x0F,
    FID_EDRIC              = 0x10,
    FID_ORELUS             = 0x11,
    FID_NURI               = 0x13,
    FID_FARID              = 0x14,
    FID_KAVRA              = 0x16,
    FID_ZAHIR              = 0x18,
    FID_BRANN              = 0x19,
    FID_KIT                = 0x1A,
    FID_MARIUS             = 0x1B,
    FID_LYRIA              = 0x1C,
    FID_MORTIVAR           = 0x1E,
    FID_VEYR               = 0x20,
    FID_KARGAN              = 0x30,
};

#endif // GUARD_CONSTANTS_FACES_H
