"""Deterministic C header/source + budget report generator.

Consumes a validated ``catalog.LoadedCatalog`` and writes, under a caller-
given output directory (always somewhere under build/ -- never a
committed source directory; see modern.mk's "Localization catalog"
section):

  * ``expansion_msg_ids.h`` -- public ``EXP_MSG_<KEY>`` numeric macros for
    every active message, for future (non-sprint-1) callers that want to
    resolve a message by a stable compile-time name instead of a raw
    numeric ExpansionMsgId.
  * ``expansion_locale_catalog.c`` -- defines the `extern const` arrays
    declared in include/expansion_locale.h (gExpansionLocaleMsgIds,
    gExpansionCatalog_en, gExpansionCatalog_qps_ploc, ...). This is the
    only generated file the modern linked build actually compiles/links;
    src/expansion_locale.c never `#include`s any generated header (see
    its own file comment), so nothing here is required for legacy (agbcc)
    compilation.
  * a budget JSON report (catalog/index/string/scratch bytes, allowed
    codepoints/glyph count, and the configured limits each is measured
    against).

Every write goes through a write-if-unchanged helper so an unrelated
rebuild never touches these files' mtimes, and generating twice from the
same registry/catalog input is always byte-for-byte identical (see
scripts/localization/tests/test_determinism.py).
"""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Dict, Tuple

from . import schema
from .catalog import LoadedCatalog, load_catalog

_NON_IDENT_RE = re.compile(r"[^A-Za-z0-9]+")


def _write_if_changed(path: Path, content: str) -> bool:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and path.read_text(encoding="utf-8") == content:
        return False
    path.write_text(content, encoding="utf-8")
    return True


def key_to_macro(key: str) -> str:
    ident = _NON_IDENT_RE.sub("_", key).strip("_").upper()
    return f"EXP_MSG_{ident}"


def _c_string_literal(text: str) -> str:
    """Encodes one ASCII catalog string as a C string literal. Only the
    two escapes sprint 1's ASCII/control-token allowlist can ever produce
    are handled: a literal backslash (never used in sprint 1 content, but
    handled for robustness) and the single supported control token
    ``\\n``; everything else in the allowed 0x20-0x7E printable range is
    emitted verbatim, and the double quote is escaped."""
    out = ['"']
    for ch in text:
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "\n":
            out.append("\\n")
        else:
            out.append(ch)
    out.append('"')
    return "".join(out)


def _assert_ids_in_range(catalog: LoadedCatalog) -> None:
    """Defensive, generator-side re-validation of every registry id
    (active and tombstone) -- independent of catalog.parse_registry's
    own source-of-truth check. This exists purely to fail loudly if a
    future caller ever constructs a LoadedCatalog/RegistryEntry directly
    (e.g. in-process, from a test, or from a not-yet-imagined future
    tool) instead of going through parse_registry()/load_catalog(): the
    generator must never silently emit an id that cannot round-trip
    through the u16 ExpansionMsgId type or that collides with the
    EXPANSION_MSG_ID_INVALID sentinel (include/expansion_locale.h).
    Raises before anything is written, so a rejected catalog never
    produces partial generated output (see generate())."""
    for entry in catalog.entries:
        entry_id = entry.id
        if isinstance(entry_id, bool) or not isinstance(entry_id, int):
            raise schema.SchemaError(
                f"message {entry.key!r} id {entry_id!r} is not an int "
                f"(generator defensive check)"
            )
        if entry_id < schema.MSG_ID_MIN or entry_id > schema.MSG_ID_MAX:
            raise schema.SchemaError(
                f"message {entry.key!r} id {entry_id} outside the assignable "
                f"ExpansionMsgId range [{schema.MSG_ID_MIN}, {schema.MSG_ID_MAX}]; "
                f"{schema.MSG_ID_INVALID} (0x{schema.MSG_ID_INVALID:04X}) is the "
                f"reserved EXPANSION_MSG_ID_INVALID sentinel and can never be "
                f"assigned to a real message (generator defensive check)"
            )


def build_msg_ids_header(catalog: LoadedCatalog) -> str:
    _assert_ids_in_range(catalog)
    lines = [
        "/* Generated by scripts/localization/generate.py -- do not edit. */",
        "/* Stable EXP_MSG_* numeric message ids (issue #18 sprint 1).",
        " * Regenerated from texts/expansion/registry.json; ids are stable",
        " * and append-only there -- see that file's own ordering. */",
        "#ifndef GUARD_EXPANSION_MSG_IDS_H",
        "#define GUARD_EXPANSION_MSG_IDS_H",
        "",
    ]
    for entry in catalog.active_entries:
        lines.append(f"#define {key_to_macro(entry.key)} {entry.id}u")
    lines.append("")
    lines.append(f"#define EXPANSION_MSG_ACTIVE_COUNT {len(catalog.active_entries)}u")
    lines.append("")
    lines.append("#endif /* GUARD_EXPANSION_MSG_IDS_H */")
    lines.append("")
    return "\n".join(lines)


def build_catalog_c(catalog: LoadedCatalog) -> str:
    _assert_ids_in_range(catalog)
    ids = [entry.id for entry in catalog.active_entries]
    en_values = [catalog.en_strings[entry.key] for entry in catalog.active_entries]
    pseudo_values = [catalog.pseudo_strings[entry.key] for entry in catalog.active_entries]

    lines = [
        "/* Generated by scripts/localization/generate.py -- do not edit. */",
        "/* Expansion framework locale catalog (issue #18 sprint 1).",
        " * Source: texts/expansion/registry.json + catalog.en.json; the",
        " * qps-ploc column is deterministically derived by",
        " * scripts/localization/pseudo.py, never hand-authored.",
        " * Defines the `extern const` data declared in",
        " * include/expansion_locale.h -- keep both in sync. */",
        '#include "global.h"',
        '#include "expansion_locale.h"',
        "",
        f"const u16 gExpansionLocaleMsgCount = {len(ids)}u;",
        f"const u16 gExpansionLocaleTombstoneCount = {len(catalog.tombstone_entries)}u;",
        "",
        "const ExpansionMsgId gExpansionLocaleMsgIds[] =",
        "{",
    ]
    for msg_id in ids:
        lines.append(f"    {msg_id}u,")
    lines.append("};")
    lines.append("")
    lines.append("const char *const gExpansionCatalog_en[] =")
    lines.append("{")
    for text in en_values:
        lines.append(f"    {_c_string_literal(text)},")
    lines.append("};")
    lines.append("")
    lines.append("const char *const gExpansionCatalog_qps_ploc[] =")
    lines.append("{")
    for text in pseudo_values:
        lines.append(f"    {_c_string_literal(text)},")
    lines.append("};")
    lines.append("")
    return "\n".join(lines)


def _codepoint_report(catalog: LoadedCatalog) -> dict:
    used = set()
    for text in list(catalog.en_strings.values()) + list(catalog.pseudo_strings.values()):
        used.update(text)
    control = sorted(ch for ch in used if ch in schema.ALLOWED_CONTROL_TOKENS)
    printable = sorted(ch for ch in used if ch not in schema.ALLOWED_CONTROL_TOKENS)
    return {
        "allowed_min_codepoint": schema.ASCII_MIN,
        "allowed_max_codepoint": schema.ASCII_MAX,
        "allowed_control_tokens": list(schema.ALLOWED_CONTROL_TOKENS),
        "glyphs_used_count": len(printable),
        "glyphs_used": ["U+%04X" % ord(ch) for ch in printable],
        "control_tokens_used": [repr(ch) for ch in control],
    }


def build_budget(catalog: LoadedCatalog) -> dict:
    ids = [entry.id for entry in catalog.active_entries]

    def encoded_len(text: str) -> int:
        return len(text.encode("ascii")) + 1  # + NUL

    en_bytes = sum(encoded_len(catalog.en_strings[e.key]) for e in catalog.active_entries)
    pseudo_bytes = sum(encoded_len(catalog.pseudo_strings[e.key]) for e in catalog.active_entries)
    max_slot_used = max(
        [encoded_len(t) for t in catalog.en_strings.values()]
        + [encoded_len(t) for t in catalog.pseudo_strings.values()],
        default=0,
    )
    index_bytes = len(ids) * 2 + len(ids) * 4 * 2  # u16 ids + 2 locales * pointer(4 bytes, GBA ARM)

    return {
        "active_message_count": len(catalog.active_entries),
        "tombstone_count": len(catalog.tombstone_entries),
        "locales_generated": ["en", schema.PSEUDO_LOCALE],
        "catalog_string_bytes": {
            "en": en_bytes,
            schema.PSEUDO_LOCALE: pseudo_bytes,
            "total": en_bytes + pseudo_bytes,
        },
        "catalog_index_bytes": index_bytes,
        "scratch_budget_bytes": schema.MAX_DECODED_BYTES_MAX,
        "scratch_slot_bytes_used_max": max_slot_used,
        "scratch_headroom_bytes": schema.MAX_DECODED_BYTES_MAX - max_slot_used,
        "codepoints": _codepoint_report(catalog),
        "limits": {
            "max_width_max": schema.MAX_WIDTH_MAX,
            "max_decoded_bytes_max": schema.MAX_DECODED_BYTES_MAX,
        },
    }


def generate(
    output_dir: Path,
    budget_json_path: Path = None,
    registry_path: Path = None,
    catalog_en_path: Path = None,
) -> Dict[str, Path]:
    kwargs = {}
    if registry_path is not None:
        kwargs["registry_path"] = registry_path
    if catalog_en_path is not None:
        kwargs["catalog_en_path"] = catalog_en_path
    catalog = load_catalog(**kwargs)

    output_dir = Path(output_dir)
    msg_ids_path = output_dir / "expansion_msg_ids.h"
    catalog_c_path = output_dir / "expansion_locale_catalog.c"

    _write_if_changed(msg_ids_path, build_msg_ids_header(catalog))
    _write_if_changed(catalog_c_path, build_catalog_c(catalog))

    budget = build_budget(catalog)
    budget_path = Path(budget_json_path) if budget_json_path is not None else output_dir / "budget.json"
    _write_if_changed(budget_path, json.dumps(budget, indent=2, sort_keys=True) + "\n")

    return {"msg_ids_header": msg_ids_path, "catalog_c": catalog_c_path, "budget_json": budget_path}
