#!/usr/bin/env python3
"""Exact, deterministic per-member source allowlist (issue #9 verifier
remediation).

``docs/release_data/source_allowlist.json`` used to grant an entire
top-level directory (e.g. ``"src"``) at once -- any file added anywhere
under an allowlisted directory was implicitly included. That is exactly
the "top-level directory allowlisting" the independent verifier flagged:
it cannot express "this specific new tracked file was never reviewed".

This module is the fix: it is the single canonical generator *and*
validator for an exact, file-level allowlist, driven directly by Git's own
tracked-file/gitlink listing (``git ls-files``, ``git ls-tree``) rather
than any second, hand-maintained notion of "the source tree". Every
regular tracked file gets its own exact entry; the ``mgfembp`` submodule
gitlink gets its own single exact entry (its *contents* are never
enumerated -- see docs/release_process.md's submodule/provenance
boundary, unchanged by this module).

``check_allowlist_completeness()`` is the fail-closed gate wired into
``scripts/release_rehearsal/manifest.py``: it is a full bijection check
between "every currently tracked file/gitlink" and "every allowlist
entry" -- a new tracked file with no allowlist entry fails exactly as
loudly as a stale allowlist entry for a file that no longer exists
(``git status``/history cannot silently drift the allowlist out of sync
with reality in either direction).

Deliberately dependency-free (Python stdlib only; reuses
``scripts/release_rehearsal/git_source.py``'s plumbing wrappers rather
than re-invoking git directly).
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path
from typing import Dict, List, Tuple

from scripts.release_rehearsal import git_source as gs

SCHEMA_VERSION = 2
DEFAULT_ALLOWLIST_PATH = Path("docs/release_data/source_allowlist.json")

# Entries this generator/checker itself never emits or expects the real
# repository allowlist to omit -- kept purely as a sanity cross-check that
# the checked-in allowlist was not hand-edited into some other shape.
_REQUIRED_TOP_LEVEL_SAMPLE = ("mgfembp",)


class AllowlistError(ValueError):
    """An actionable schema/consistency defect in the allowlist file
    itself (distinct from a normal "these files are unlisted" finding,
    which is reported as a list of strings, not raised)."""


def generate_entries(repo_root: Path, target_sha: str) -> List[str]:
    """Exact, deterministic (git-tree-ordered) list of every path that
    must appear in the allowlist for `target_sha`: every blob-mode tree
    entry (regular file or executable; a tracked *symlink*, if one is ever
    added, is deliberately still listed here too -- omitting it would only
    hide the problem, and `source_guard.py`'s own hard-deny check is what
    actually rejects it) plus every gitlink (submodule mountpoint) path
    as its own single, exact entry (never its contents)."""
    entries = [entry.path for entry in gs.list_tree(repo_root, target_sha)]
    return sorted(entries)


def generate_allowlist_document(repo_root: Path, target_sha: str) -> Dict:
    entries = generate_entries(repo_root, target_sha)
    return {
        "_comment": (
            "Exact, deterministic, per-member source-release allowlist (issue #9 "
            "verifier remediation). Every entry is one exact repo-relative tracked "
            "file path, or the single 'mgfembp' submodule gitlink path -- there is "
            "no directory-level/prefix grant any more. Generated by "
            "'python3 -m scripts.release_rehearsal.allowlist generate'; regenerate "
            "and commit this file whenever a tracked file is added, renamed, or "
            "removed (`make release-check` / `python3 -m "
            "scripts.release_rehearsal.allowlist check` fails actionably if this "
            "file and the actual tracked-file set ever disagree). This is a "
            "structural membership allowlist only -- see "
            "docs/release_data/provenance/*.json and docs/release_process.md for "
            "the separate, currently-unresolved legal/provenance determination "
            "that independently blocks publication regardless of this allowlist."
        ),
        "schema_version": SCHEMA_VERSION,
        "generated_from_sha": target_sha,
        "generator": "python3 -m scripts.release_rehearsal.allowlist generate",
        "paths": entries,
    }


def load_allowlist_paths(path: Path) -> List[str]:
    try:
        data = json.loads(Path(path).read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as error:
        raise AllowlistError(f"{path}: not valid JSON: {error}") from error
    paths = data.get("paths")
    if not isinstance(paths, list) or not paths:
        raise AllowlistError(f"{path}: must contain a non-empty 'paths' array")
    if len(paths) != len(set(paths)):
        seen = set()
        dupes = sorted({p for p in paths if (p in seen or seen.add(p))})
        raise AllowlistError(f"{path}: duplicate entries: {dupes}")
    return paths


def check_allowlist_completeness(
    repo_root: Path, allowlist_paths: List[str], target_sha: str = "HEAD"
) -> Tuple[List[str], List[str]]:
    """Full bijection check between the exact, resolved tracked-file/
    gitlink set at `target_sha` and `allowlist_paths`. Returns
    `(missing, stale)`:

    * `missing` -- tracked paths with **no** allowlist entry at all (the
      literal "a new/unlisted tracked file must fail" case).
    * `stale` -- allowlist entries that do not correspond to any currently
      tracked path (a "ghost"/stale entry left behind after a file was
      renamed or deleted -- allowed to drift silently, this would let the
      allowlist quietly grow stale forever and no longer reflect reality).

    Both must be empty for a well-formed, exactly-synchronized allowlist.
    """
    tracked = {entry.path for entry in gs.list_tree(repo_root, target_sha)}
    allowlist_set = set(allowlist_paths)
    missing = sorted(tracked - allowlist_set)
    stale = sorted(allowlist_set - tracked)
    return missing, stale


def _present_regular_files(repo_root: Path) -> List[str]:
    """Every ordinary, non-symlink regular file's repo-relative posix
    path actually present on disk under `repo_root` -- the non-git
    equivalent of a tracked-file listing, used **only** when `repo_root`
    has no `.git` metadata at all (`git_source.is_git_repo` is False; a
    genuine extracted archive/non-git candidate tree). Never invokes git
    -- issue #9 verifier remediation: a non-git candidate tree must never
    have git plumbing invoked against it (which could otherwise silently
    walk *upward* to an unrelated enclosing repository and report *that*
    repository's tracked files instead of failing closed). Mirrors
    scripts/release_rehearsal/source_guard.py's own tree-walk convention
    (skip a root-level ".git", never follow symlinks)."""
    repo_root = Path(repo_root)
    present: List[str] = []
    for dirpath, dirnames, filenames in os.walk(repo_root, followlinks=False):
        dirpath_path = Path(dirpath)
        if dirpath_path == repo_root:
            dirnames[:] = [d for d in dirnames if d != ".git"]
        for name in filenames:
            full = dirpath_path / name
            if full.is_symlink():
                continue
            present.append(full.relative_to(repo_root).as_posix())
    return present


def _entry_has_on_disk_representation(repo_root: Path, entry: str) -> bool:
    """True if allowlist entry `entry` corresponds to *some* real,
    non-symlink file or directory in a non-git candidate tree. A
    directory match covers a gitlink-style mountpoint (e.g. the
    "mgfembp" submodule path): a real git-tracked tree always records
    that path as its own tree entry with no blob content at all (see
    git_source.py's MODE_GITLINK), and a genuine extracted archive
    (e.g. GitHub's auto-generated source archive) materializes it as an
    empty directory -- it is never itself required to contain
    anything, exactly like a real gitlink. A symlink at `entry` never
    counts as a representation (consistent with
    `_filesystem_allowlisted_files`, which also never treats a symlink
    as safe content)."""
    candidate = Path(repo_root) / entry
    if candidate.is_symlink():
        return False
    return candidate.is_file() or candidate.is_dir()


def check_allowlist_completeness_non_git(
    repo_root: Path, allowlist_paths: List[str]
) -> Tuple[List[str], List[str]]:
    """The non-git analogue of `check_allowlist_completeness`, used
    **only** when `repo_root` has no `.git` at all (a genuine extracted
    archive/non-git candidate tree -- see `git_source.is_git_repo`).
    There is no git-tracked-file notion to consult here at all -- issue
    #9 verifier remediation requires this to closed-world-validate the
    *actual on-disk membership* of the extracted tree against the
    checked-in allowlist instead, and to never invoke git plumbing
    against such a tree (there is nothing to invoke it against, and
    doing so anyway could silently produce a result bound to an
    unrelated enclosing repository rather than this tree). Returns
    `(missing, unrepresented)`:

    * `missing` -- an ordinary regular file physically present in the
      extracted tree whose own exact path has no allowlist entry at all
      (the non-git analogue of "a new/unlisted tracked file").
    * `unrepresented` -- an allowlist entry with **no** on-disk
      representation whatsoever in this extracted tree -- neither as a
      regular file nor (for a gitlink-style entry such as the "mgfembp"
      submodule mountpoint) as a directory. This is the precise
      "missing/unrepresented gitlink/mgfembp" blocker a genuine
      extracted candidate must report rather than silently ignore.

    A directory is never itself required to have its *contents*
    individually re-validated here (mirrors
    scripts/release_rehearsal/source_guard.py's "structural parent
    only, never an authorization prefix" rule) -- only whether the
    allowlisted path itself has *some* real, non-symlink on-disk form.
    """
    present_files = set(_present_regular_files(repo_root))
    allowlist_set = set(allowlist_paths)
    missing = sorted(present_files - allowlist_set)
    unrepresented = sorted(
        entry for entry in allowlist_set
        if not _entry_has_on_disk_representation(repo_root, entry)
    )
    return missing, unrepresented


def check(repo_root: Path, allowlist_path: Path, target_sha: str = "HEAD") -> List[str]:
    """Convenience wrapper returning a flat, human-readable error list
    (empty means fully consistent); used by both the CLI and
    scripts/release_rehearsal/manifest.py.

    Dispatches on whether `repo_root` actually is a git repository
    (`git_source.is_git_repo`) -- issue #9 verifier remediation: a
    non-git candidate tree (a genuine extracted archive) is
    closed-world-validated against on-disk membership
    (`check_allowlist_completeness_non_git`) and never causes a `git`
    invocation at all; only a real git working tree uses
    `check_allowlist_completeness`'s git-tracked-file bijection. A
    well-formed 40-lowercase-hex `target_sha` that does not resolve to a
    real object in an actual git repository still raises
    `git_source.GitSourceError` here (propagated, never swallowed into a
    soft warning): that is an actionable input defect for the CLI's
    single top-level exception boundary to convert into
    `EXIT_TOOLING_ERROR`, not an honestly-recorded business fact."""
    try:
        allowlist_paths = load_allowlist_paths(allowlist_path)
    except AllowlistError as error:
        return [str(error)]
    repo_root = Path(repo_root)
    if not gs.is_git_repo(repo_root):
        missing, unrepresented = check_allowlist_completeness_non_git(repo_root, allowlist_paths)
        errors = [
            f"file present in extracted tree but missing from allowlist: {path}"
            for path in missing
        ]
        errors += [
            "allowlisted member has no on-disk representation in this extracted tree "
            f"(missing/unrepresented -- e.g. an absent gitlink mountpoint such as "
            f"'mgfembp', or a removed/never-extracted file): {path}"
            for path in unrepresented
        ]
        return errors
    missing, stale = check_allowlist_completeness(repo_root, allowlist_paths, target_sha)
    errors = [f"tracked file missing from allowlist: {path}" for path in missing]
    errors += [f"stale allowlist entry (no longer tracked): {path}" for path in stale]
    return errors


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    sub = parser.add_subparsers(dest="command", required=True)

    common = argparse.ArgumentParser(add_help=False)
    common.add_argument("--repo-root", type=Path, default=Path("."))
    common.add_argument("--allowlist", type=Path, default=DEFAULT_ALLOWLIST_PATH)
    common.add_argument(
        "--target-sha", default="HEAD",
        help="a commit-ish (default HEAD), or the literal 'index' to use the "
             "current staged index (via 'git write-tree') -- a development-time "
             "convenience for generating/checking the allowlist before committing",
    )

    sub.add_parser("check", parents=[common], help="verify the checked-in allowlist is exact")
    gen = sub.add_parser("generate", parents=[common], help="print a freshly-generated allowlist document")
    gen.add_argument("--write", action="store_true", help="write the result to --allowlist instead of stdout")

    args = parser.parse_args(argv)

    try:
        if args.target_sha == "index":
            target_sha = gs.write_index_tree(args.repo_root)
        else:
            target_sha = gs.resolve_sha(args.repo_root, args.target_sha)
    except gs.GitSourceError as error:
        print(f"error: {error}", file=sys.stderr)
        return 2

    if args.command == "generate":
        document = generate_allowlist_document(args.repo_root, target_sha)
        text = json.dumps(document, indent=2, sort_keys=False) + "\n"
        if args.write:
            args.allowlist.write_text(text, encoding="utf-8")
            print(f"wrote {len(document['paths'])} entries to {args.allowlist}", file=sys.stderr)
        else:
            sys.stdout.write(text)
        return 0

    errors = check(args.repo_root, args.allowlist, target_sha)
    if errors:
        for error in errors:
            print(f"error: {error}", file=sys.stderr)
        print(f"allowlist: {len(errors)} inconsistency(ies) against {target_sha}", file=sys.stderr)
        return 1
    print(f"allowlist: ok (exact match against {target_sha})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
