#!/usr/bin/env python3
"""Exact, deterministic per-member source allowlist (issue #9 verifier
remediation).

``docs/release_data/source_allowlist.json`` used to grant an entire
top-level directory (e.g. ``"src"``) at once -- any file added anywhere
under an allowlisted directory was implicitly included. That is exactly
the "top-level directory allowlisting" the independent verifier flagged:
it cannot express "this specific new tracked file was never reviewed".

This module is the fix: it is the single canonical generator *and*
validator for an exact, file-level allowlist, driven directly by Git's own
tracked-file/gitlink listing (``git ls-files``, ``git ls-tree``) rather
than any second, hand-maintained notion of "the source tree". Every
regular tracked file gets its own exact entry; the ``mgfembp`` submodule
gitlink gets its own single exact entry (its *contents* are never
enumerated -- see docs/release_process.md's submodule/provenance
boundary, unchanged by this module).

``check_allowlist_completeness()`` is the fail-closed gate wired into
``scripts/release_rehearsal/manifest.py``: it is a full bijection check
between "every currently tracked file/gitlink" and "every allowlist
entry" -- a new tracked file with no allowlist entry fails exactly as
loudly as a stale allowlist entry for a file that no longer exists
(``git status``/history cannot silently drift the allowlist out of sync
with reality in either direction).

Deliberately dependency-free (Python stdlib only; reuses
``scripts/release_rehearsal/git_source.py``'s plumbing wrappers rather
than re-invoking git directly).
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Dict, List, Tuple

from scripts.release_rehearsal import git_source as gs

SCHEMA_VERSION = 2
DEFAULT_ALLOWLIST_PATH = Path("docs/release_data/source_allowlist.json")

# Entries this generator/checker itself never emits or expects the real
# repository allowlist to omit -- kept purely as a sanity cross-check that
# the checked-in allowlist was not hand-edited into some other shape.
_REQUIRED_TOP_LEVEL_SAMPLE = ("mgfembp",)


class AllowlistError(ValueError):
    """An actionable schema/consistency defect in the allowlist file
    itself (distinct from a normal "these files are unlisted" finding,
    which is reported as a list of strings, not raised)."""


def generate_entries(repo_root: Path, target_sha: str) -> List[str]:
    """Exact, deterministic (git-tree-ordered) list of every path that
    must appear in the allowlist for `target_sha`: every blob-mode tree
    entry (regular file or executable; a tracked *symlink*, if one is ever
    added, is deliberately still listed here too -- omitting it would only
    hide the problem, and `source_guard.py`'s own hard-deny check is what
    actually rejects it) plus every gitlink (submodule mountpoint) path
    as its own single, exact entry (never its contents)."""
    entries = [entry.path for entry in gs.list_tree(repo_root, target_sha)]
    return sorted(entries)


def generate_allowlist_document(repo_root: Path, target_sha: str) -> Dict:
    entries = generate_entries(repo_root, target_sha)
    return {
        "_comment": (
            "Exact, deterministic, per-member source-release allowlist (issue #9 "
            "verifier remediation). Every entry is one exact repo-relative tracked "
            "file path, or the single 'mgfembp' submodule gitlink path -- there is "
            "no directory-level/prefix grant any more. Generated by "
            "'python3 -m scripts.release_rehearsal.allowlist generate'; regenerate "
            "and commit this file whenever a tracked file is added, renamed, or "
            "removed (`make release-check` / `python3 -m "
            "scripts.release_rehearsal.allowlist check` fails actionably if this "
            "file and the actual tracked-file set ever disagree). This is a "
            "structural membership allowlist only -- see "
            "docs/release_data/provenance/*.json and docs/release_process.md for "
            "the separate, currently-unresolved legal/provenance determination "
            "that independently blocks publication regardless of this allowlist."
        ),
        "schema_version": SCHEMA_VERSION,
        "generated_from_sha": target_sha,
        "generator": "python3 -m scripts.release_rehearsal.allowlist generate",
        "paths": entries,
    }


def load_allowlist_paths(path: Path) -> List[str]:
    try:
        data = json.loads(Path(path).read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as error:
        raise AllowlistError(f"{path}: not valid JSON: {error}") from error
    paths = data.get("paths")
    if not isinstance(paths, list) or not paths:
        raise AllowlistError(f"{path}: must contain a non-empty 'paths' array")
    if len(paths) != len(set(paths)):
        seen = set()
        dupes = sorted({p for p in paths if (p in seen or seen.add(p))})
        raise AllowlistError(f"{path}: duplicate entries: {dupes}")
    return paths


def check_allowlist_completeness(
    repo_root: Path, allowlist_paths: List[str], target_sha: str = "HEAD"
) -> Tuple[List[str], List[str]]:
    """Full bijection check between the exact, resolved tracked-file/
    gitlink set at `target_sha` and `allowlist_paths`. Returns
    `(missing, stale)`:

    * `missing` -- tracked paths with **no** allowlist entry at all (the
      literal "a new/unlisted tracked file must fail" case).
    * `stale` -- allowlist entries that do not correspond to any currently
      tracked path (a "ghost"/stale entry left behind after a file was
      renamed or deleted -- allowed to drift silently, this would let the
      allowlist quietly grow stale forever and no longer reflect reality).

    Both must be empty for a well-formed, exactly-synchronized allowlist.
    """
    tracked = {entry.path for entry in gs.list_tree(repo_root, target_sha)}
    allowlist_set = set(allowlist_paths)
    missing = sorted(tracked - allowlist_set)
    stale = sorted(allowlist_set - tracked)
    return missing, stale


def check(repo_root: Path, allowlist_path: Path, target_sha: str = "HEAD") -> List[str]:
    """Convenience wrapper returning a flat, human-readable error list
    (empty means fully consistent); used by both the CLI and
    scripts/release_rehearsal/manifest.py."""
    try:
        allowlist_paths = load_allowlist_paths(allowlist_path)
    except AllowlistError as error:
        return [str(error)]
    missing, stale = check_allowlist_completeness(repo_root, allowlist_paths, target_sha)
    errors = [f"tracked file missing from allowlist: {path}" for path in missing]
    errors += [f"stale allowlist entry (no longer tracked): {path}" for path in stale]
    return errors


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    sub = parser.add_subparsers(dest="command", required=True)

    common = argparse.ArgumentParser(add_help=False)
    common.add_argument("--repo-root", type=Path, default=Path("."))
    common.add_argument("--allowlist", type=Path, default=DEFAULT_ALLOWLIST_PATH)
    common.add_argument(
        "--target-sha", default="HEAD",
        help="a commit-ish (default HEAD), or the literal 'index' to use the "
             "current staged index (via 'git write-tree') -- a development-time "
             "convenience for generating/checking the allowlist before committing",
    )

    sub.add_parser("check", parents=[common], help="verify the checked-in allowlist is exact")
    gen = sub.add_parser("generate", parents=[common], help="print a freshly-generated allowlist document")
    gen.add_argument("--write", action="store_true", help="write the result to --allowlist instead of stdout")

    args = parser.parse_args(argv)

    try:
        if args.target_sha == "index":
            target_sha = gs.write_index_tree(args.repo_root)
        else:
            target_sha = gs.resolve_sha(args.repo_root, args.target_sha)
    except gs.GitSourceError as error:
        print(f"error: {error}", file=sys.stderr)
        return 2

    if args.command == "generate":
        document = generate_allowlist_document(args.repo_root, target_sha)
        text = json.dumps(document, indent=2, sort_keys=False) + "\n"
        if args.write:
            args.allowlist.write_text(text, encoding="utf-8")
            print(f"wrote {len(document['paths'])} entries to {args.allowlist}", file=sys.stderr)
        else:
            sys.stdout.write(text)
        return 0

    errors = check(args.repo_root, args.allowlist, target_sha)
    if errors:
        for error in errors:
            print(f"error: {error}", file=sys.stderr)
        print(f"allowlist: {len(errors)} inconsistency(ies) against {target_sha}", file=sys.stderr)
        return 1
    print(f"allowlist: ok (exact match against {target_sha})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
