    .byte 0, 8, 0, 3, 3, 0, 0, 0
    .word Ch10EphraimMapChanges_change_0
    .byte 1, 3, 10, 3, 3, 0, 0, 0
    .word Ch10EphraimMapChanges_change_1
    .byte 2, 5, 1, 1, 1, 0, 0, 0
    .word Ch10EphraimMapChanges_change_2
    .byte 3, 6, 0, 1, 1, 0, 0, 0
    .word Ch10EphraimMapChanges_change_3
    .byte 4, 9, 2, 1, 1, 0, 0, 0
    .word Ch10EphraimMapChanges_change_4
    .byte 5, 4, 12, 1, 1, 0, 0, 0
    .word Ch10EphraimMapChanges_change_5
    .byte 6, 8, 14, 1, 1, 0, 0, 0
    .word Ch10EphraimMapChanges_change_6
    .byte 7, 9, 14, 1, 1, 0, 0, 0
    .word Ch10EphraimMapChanges_change_7
    .word 0xff, 0, 0
