    .byte 0, 19, 0, 6, 10, 0, 0, 0
    .word Ch14EirikaMapChanges_change_0
    .byte 1, 21, 11, 3, 7, 0, 0, 0
    .word Ch14EirikaMapChanges_change_1
    .byte 2, 17, 2, 2, 1, 0, 0, 0
    .word Ch14EirikaMapChanges_change_2
    .byte 3, 16, 14, 4, 6, 0, 0, 0
    .word Ch14EirikaMapChanges_change_3
    .byte 4, 10, 14, 1, 1, 0, 0, 0
    .word Ch14EirikaMapChanges_change_4
    .byte 5, 6, 19, 7, 6, 0, 0, 0
    .word Ch14EirikaMapChanges_change_5
    .byte 6, 1, 14, 4, 6, 0, 0, 0
    .word Ch14EirikaMapChanges_change_6
    .byte 7, 22, 3, 1, 1, 0, 0, 0
    .word Ch14EirikaMapChanges_change_7
    .byte 8, 22, 5, 1, 1, 0, 0, 0
    .word Ch14EirikaMapChanges_change_8
    .byte 9, 20, 11, 4, 6, 0, 0, 0
    .word Ch14EirikaMapChanges_change_9
    .byte 10, 18, 16, 1, 1, 0, 0, 0
    .word Ch14EirikaMapChanges_change_10
    .byte 11, 8, 20, 1, 1, 0, 0, 0
    .word Ch14EirikaMapChanges_change_11
    .byte 12, 2, 16, 1, 1, 0, 0, 0
    .word Ch14EirikaMapChanges_change_12
    .byte 13, 10, 20, 1, 1, 0, 0, 0
    .word Ch14EirikaMapChanges_change_13
    .word 0xff, 0, 0
