    .byte 0, 13, 7, 3, 2, 0, 0, 0
    .word Ch14EphraimMapChanges_change_0
    .byte 1, 6, 12, 3, 3, 0, 0, 0
    .word Ch14EphraimMapChanges_change_1
    .byte 2, 20, 12, 3, 3, 0, 0, 0
    .word Ch14EphraimMapChanges_change_2
    .byte 3, 13, 20, 3, 2, 0, 0, 0
    .word Ch14EphraimMapChanges_change_3
    .byte 4, 13, 18, 1, 1, 0, 0, 0
    .word Ch14EphraimMapChanges_change_4
    .byte 5, 15, 18, 1, 1, 0, 0, 0
    .word Ch14EphraimMapChanges_change_5
    .byte 6, 3, 1, 1, 1, 0, 0, 0
    .word Ch14EphraimMapChanges_change_6
    .byte 7, 27, 1, 1, 1, 0, 0, 0
    .word Ch14EphraimMapChanges_change_7
    .byte 8, 14, 18, 1, 1, 0, 0, 0
    .word Ch14EphraimMapChanges_change_8
    .word 0xff, 0, 0
