    .byte 0, 3, 3, 2, 2, 0, 0, 0
    .word Ch16MapChanges_change_0
    .byte 1, 2, 10, 3, 2, 0, 0, 0
    .word Ch16MapChanges_change_1
    .byte 2, 3, 12, 1, 1, 0, 0, 0
    .word Ch16MapChanges_change_2
    .byte 3, 20, 1, 1, 1, 0, 0, 0
    .word Ch16MapChanges_change_3
    .byte 4, 20, 3, 1, 1, 0, 0, 0
    .word Ch16MapChanges_change_4
    .byte 5, 1, 4, 1, 1, 0, 0, 0
    .word Ch16MapChanges_change_5
    .byte 6, 20, 5, 1, 1, 0, 0, 0
    .word Ch16MapChanges_change_6
    .byte 7, 13, 2, 1, 2, 0, 0, 0
    .word Ch16MapChanges_change_7
    .byte 8, 14, 2, 2, 2, 0, 0, 0
    .word Ch16MapChanges_change_8
    .word 0xff, 0, 0
