    .byte 0, 2, 11, 1, 1, 0, 0, 0
    .word Ch19MapChanges_change_0
    .byte 1, 3, 12, 1, 1, 0, 0, 0
    .word Ch19MapChanges_change_1
    .byte 2, 4, 11, 1, 1, 0, 0, 0
    .word Ch19MapChanges_change_2
    .byte 3, 27, 10, 1, 1, 0, 0, 0
    .word Ch19MapChanges_change_3
    .byte 4, 27, 12, 1, 1, 0, 0, 0
    .word Ch19MapChanges_change_4
    .byte 5, 27, 14, 1, 1, 0, 0, 0
    .word Ch19MapChanges_change_5
    .byte 6, 3, 15, 1, 2, 0, 0, 0
    .word Ch19MapChanges_change_6
    .word 0xff, 0, 0
