    .byte 0, 4, 8, 2, 2, 0, 0, 0
    .word Ch3MapChanges_change_0
    .byte 1, 4, 11, 2, 2, 0, 0, 0
    .word Ch3MapChanges_change_1
    .byte 2, 8, 7, 2, 2, 0, 0, 0
    .word Ch3MapChanges_change_2
    .byte 3, 2, 3, 1, 2, 0, 0, 0
    .word Ch3MapChanges_change_3
    .byte 4, 6, 10, 1, 1, 0, 0, 0
    .word Ch3MapChanges_change_4
    .byte 5, 10, 5, 1, 1, 0, 0, 0
    .word Ch3MapChanges_change_5
    .byte 6, 6, 3, 1, 1, 0, 0, 0
    .word Ch3MapChanges_change_6
    .byte 7, 8, 3, 1, 1, 0, 0, 0
    .word Ch3MapChanges_change_7
    .byte 8, 10, 3, 1, 1, 0, 0, 0
    .word Ch3MapChanges_change_8
    .byte 9, 6, 12, 1, 1, 0, 0, 0
    .word Ch3MapChanges_change_9
    .word 0xff, 0, 0
