    .byte 0, 7, 0, 3, 3, 0, 0, 0
    .word Ch4MapChanges_change_0
    .byte 1, 4, 8, 1, 3, 0, 0, 0
    .word Ch4MapChanges_change_1
    .byte 2, 0, 9, 3, 3, 0, 0, 0
    .word Ch4MapChanges_change_2
    .byte 3, 8, 2, 1, 1, 0, 0, 0
    .word Ch4MapChanges_change_3
    .byte 4, 4, 8, 1, 3, 0, 0, 0
    .word Ch4MapChanges_change_4
    .byte 5, 1, 11, 1, 1, 0, 0, 0
    .word Ch4MapChanges_change_5
    .word 0xff, 0, 0
