    .byte 0, 4, 0, 3, 2, 0, 0, 0
    .word Ch5MapChanges_change_0
    .byte 1, 4, 5, 3, 2, 0, 0, 0
    .word Ch5MapChanges_change_1
    .byte 2, 11, 9, 3, 2, 0, 0, 0
    .word Ch5MapChanges_change_2
    .byte 3, 11, 18, 3, 2, 0, 0, 0
    .word Ch5MapChanges_change_3
    .byte 4, 5, 1, 1, 1, 0, 0, 0
    .word Ch5MapChanges_change_4
    .byte 5, 5, 6, 1, 1, 0, 0, 0
    .word Ch5MapChanges_change_5
    .byte 6, 12, 10, 1, 1, 0, 0, 0
    .word Ch5MapChanges_change_6
    .byte 7, 12, 19, 1, 1, 0, 0, 0
    .word Ch5MapChanges_change_7
    .word 0xff, 0, 0
