    .byte 0, 20, 7, 1, 1, 0, 0, 0
    .word Ch8MapChanges_change_0
    .byte 1, 4, 6, 2, 3, 0, 0, 0
    .word Ch8MapChanges_change_1
    .byte 2, 1, 5, 1, 1, 0, 0, 0
    .word Ch8MapChanges_change_2
    .byte 3, 1, 3, 1, 1, 0, 0, 0
    .word Ch8MapChanges_change_3
    .byte 4, 2, 3, 1, 1, 0, 0, 0
    .word Ch8MapChanges_change_4
    .byte 5, 18, 21, 4, 3, 0, 0, 0
    .word Ch8MapChanges_change_5
    .byte 6, 19, 4, 1, 1, 0, 0, 0
    .word Ch8MapChanges_change_6
    .word 0xff, 0, 0
