    .byte 0, 12, 17, 2, 2, 0, 0, 0
    .word Ch9EphMapChanges_change_0
    .byte 1, 13, 1, 2, 2, 0, 0, 0
    .word Ch9EphMapChanges_change_1
    .byte 2, 12, 3, 1, 2, 0, 0, 0
    .word Ch9EphMapChanges_change_2
    .byte 3, 7, 1, 1, 1, 0, 0, 0
    .word Ch9EphMapChanges_change_3
    .byte 4, 18, 1, 1, 1, 0, 0, 0
    .word Ch9EphMapChanges_change_4
    .byte 5, 23, 1, 1, 1, 0, 0, 0
    .word Ch9EphMapChanges_change_5
    .word 0xff, 0, 0
