    .byte 0, 4, 4, 1, 1, 0, 0, 0
    .word LagdouRuins5MapChanges_change_0
    .byte 1, 13, 10, 1, 1, 0, 0, 0
    .word LagdouRuins5MapChanges_change_1
    .byte 2, 17, 21, 1, 1, 0, 0, 0
    .word LagdouRuins5MapChanges_change_2
    .byte 3, 0, 6, 2, 3, 0, 0, 0
    .word LagdouRuins5MapChanges_change_3
    .byte 4, 8, 5, 2, 3, 0, 0, 0
    .word LagdouRuins5MapChanges_change_4
    .word 0xff, 0, 0
