    .byte 0, 1, 2, 1, 1, 0, 0, 0
    .word LagdouRuins3MapChanges_change_0
    .byte 1, 3, 1, 2, 2, 0, 0, 0
    .word LagdouRuins3MapChanges_change_1
    .byte 2, 1, 7, 1, 1, 0, 0, 0
    .word LagdouRuins3MapChanges_change_2
    .byte 3, 8, 6, 2, 1, 0, 0, 0
    .word LagdouRuins3MapChanges_change_3
    .byte 4, 14, 0, 3, 2, 0, 0, 0
    .word LagdouRuins3MapChanges_change_4
    .byte 5, 15, 3, 2, 2, 0, 0, 0
    .word LagdouRuins3MapChanges_change_5
    .byte 6, 17, 3, 1, 1, 0, 0, 0
    .word LagdouRuins3MapChanges_change_6
    .byte 7, 17, 8, 1, 1, 0, 0, 0
    .word LagdouRuins3MapChanges_change_7
    .byte 8, 8, 10, 1, 2, 0, 0, 0
    .word LagdouRuins3MapChanges_change_8
    .byte 9, 1, 15, 1, 2, 0, 0, 0
    .word LagdouRuins3MapChanges_change_9
    .byte 10, 1, 22, 1, 1, 0, 0, 0
    .word LagdouRuins3MapChanges_change_10
    .byte 11, 15, 15, 1, 1, 0, 0, 0
    .word LagdouRuins3MapChanges_change_11
    .byte 12, 17, 13, 2, 2, 0, 0, 0
    .word LagdouRuins3MapChanges_change_12
    .word 0xff, 0, 0
