    .byte 0, 0, 15, 2, 3, 0, 0, 0
    .word LagdouRuins8MapChanges_change_0
    .byte 1, 0, 10, 3, 2, 0, 0, 0
    .word LagdouRuins8MapChanges_change_1
    .byte 2, 0, 3, 7, 2, 0, 0, 0
    .word LagdouRuins8MapChanges_change_2
    .byte 3, 5, 19, 1, 2, 0, 0, 0
    .word LagdouRuins8MapChanges_change_3
    .byte 4, 9, 15, 3, 4, 0, 0, 0
    .word LagdouRuins8MapChanges_change_4
    .byte 5, 9, 9, 3, 2, 0, 0, 0
    .word LagdouRuins8MapChanges_change_5
    .byte 6, 9, 6, 3, 1, 0, 0, 0
    .word LagdouRuins8MapChanges_change_6
    .byte 7, 12, 11, 3, 2, 0, 0, 0
    .word LagdouRuins8MapChanges_change_7
    .byte 8, 11, 20, 2, 1, 0, 0, 0
    .word LagdouRuins8MapChanges_change_8
    .byte 9, 15, 13, 5, 2, 0, 0, 0
    .word LagdouRuins8MapChanges_change_9
    .byte 10, 16, 7, 3, 1, 0, 0, 0
    .word LagdouRuins8MapChanges_change_10
    .byte 11, 4, 16, 2, 2, 0, 0, 0
    .word LagdouRuins8MapChanges_change_11
    .byte 12, 4, 12, 1, 1, 0, 0, 0
    .word LagdouRuins8MapChanges_change_12
    .byte 13, 16, 5, 2, 1, 0, 0, 0
    .word LagdouRuins8MapChanges_change_13
    .word 0xff, 0, 0
