    .byte 0, 4, 3, 2, 3, 0, 0, 0
    .word LagdouRuins4MapChanges_change_0
    .byte 1, 12, 2, 3, 3, 0, 0, 0
    .word LagdouRuins4MapChanges_change_1
    .byte 2, 18, 2, 1, 1, 0, 0, 0
    .word LagdouRuins4MapChanges_change_2
    .byte 3, 1, 26, 1, 1, 0, 0, 0
    .word LagdouRuins4MapChanges_change_3
    .byte 4, 1, 9, 2, 3, 0, 0, 0
    .word LagdouRuins4MapChanges_change_4
    .byte 5, 7, 9, 3, 3, 0, 0, 0
    .word LagdouRuins4MapChanges_change_5
    .byte 6, 12, 9, 2, 3, 0, 0, 0
    .word LagdouRuins4MapChanges_change_6
    .byte 7, 1, 13, 2, 3, 0, 0, 0
    .word LagdouRuins4MapChanges_change_7
    .byte 8, 4, 9, 2, 3, 0, 0, 0
    .word LagdouRuins4MapChanges_change_8
    .byte 9, 6, 13, 2, 3, 0, 0, 0
    .word LagdouRuins4MapChanges_change_9
    .byte 10, 11, 13, 2, 3, 0, 0, 0
    .word LagdouRuins4MapChanges_change_10
    .byte 11, 4, 17, 2, 3, 0, 0, 0
    .word LagdouRuins4MapChanges_change_11
    .byte 12, 7, 16, 3, 3, 0, 0, 0
    .word LagdouRuins4MapChanges_change_12
    .byte 13, 14, 16, 2, 3, 0, 0, 0
    .word LagdouRuins4MapChanges_change_13
    .byte 14, 16, 15, 3, 3, 0, 0, 0
    .word LagdouRuins4MapChanges_change_14
    .byte 15, 6, 20, 2, 3, 0, 0, 0
    .word LagdouRuins4MapChanges_change_15
    .byte 16, 11, 20, 2, 3, 0, 0, 0
    .word LagdouRuins4MapChanges_change_16
    .byte 17, 9, 24, 2, 3, 0, 0, 0
    .word LagdouRuins4MapChanges_change_17
    .word 0xff, 0, 0
