    .byte 0, 9, 13, 1, 7, 0, 0, 0
    .word TowerOfValni7MapChanges_change_0
    .byte 1, 17, 12, 1, 8, 0, 0, 0
    .word TowerOfValni7MapChanges_change_1
    .byte 2, 22, 4, 2, 11, 0, 0, 0
    .word TowerOfValni7MapChanges_change_2
    .byte 3, 12, 2, 1, 4, 0, 0, 0
    .word TowerOfValni7MapChanges_change_3
    .byte 4, 4, 2, 3, 2, 0, 0, 0
    .word TowerOfValni7MapChanges_change_4
    .word 0xff, 0, 0
