    .byte 0, 5, 3, 2, 3, 0, 0, 0
    .word TowerOfValni6MapChanges_change_0
    .byte 1, 8, 0, 2, 3, 0, 0, 0
    .word TowerOfValni6MapChanges_change_1
    .byte 2, 10, 1, 1, 1, 0, 0, 0
    .word TowerOfValni6MapChanges_change_2
    .byte 3, 12, 1, 1, 1, 0, 0, 0
    .word TowerOfValni6MapChanges_change_3
    .byte 4, 4, 8, 2, 3, 0, 0, 0
    .word TowerOfValni6MapChanges_change_4
    .byte 5, 9, 6, 3, 3, 0, 0, 0
    .word TowerOfValni6MapChanges_change_5
    .byte 6, 14, 6, 3, 3, 0, 0, 0
    .word TowerOfValni6MapChanges_change_6
    .byte 7, 7, 11, 2, 3, 0, 0, 0
    .word TowerOfValni6MapChanges_change_7
    .byte 8, 13, 9, 2, 3, 0, 0, 0
    .word TowerOfValni6MapChanges_change_8
    .byte 9, 17, 9, 2, 3, 0, 0, 0
    .word TowerOfValni6MapChanges_change_9
    .byte 10, 2, 18, 1, 1, 0, 0, 0
    .word TowerOfValni6MapChanges_change_10
    .byte 11, 4, 16, 2, 3, 0, 0, 0
    .word TowerOfValni6MapChanges_change_11
    .byte 12, 7, 16, 2, 3, 0, 0, 0
    .word TowerOfValni6MapChanges_change_12
    .byte 13, 10, 16, 2, 3, 0, 0, 0
    .word TowerOfValni6MapChanges_change_13
    .byte 14, 16, 16, 2, 3, 0, 0, 0
    .word TowerOfValni6MapChanges_change_14
    .byte 15, 18, 16, 2, 3, 0, 0, 0
    .word TowerOfValni6MapChanges_change_15
    .byte 16, 19, 1, 1, 1, 0, 0, 0
    .word TowerOfValni6MapChanges_change_16
    .word 0xff, 0, 0
