    .byte 0, 14, 10, 1, 1, 0, 0, 0
    .word UnusedMapChanges11_change_0
    .byte 1, 13, 10, 1, 1, 0, 0, 0
    .word UnusedMapChanges11_change_1
    .byte 2, 12, 10, 1, 1, 0, 0, 0
    .word UnusedMapChanges11_change_2
    .byte 3, 11, 10, 1, 1, 0, 0, 0
    .word UnusedMapChanges11_change_3
    .byte 4, 14, 11, 1, 1, 0, 0, 0
    .word UnusedMapChanges11_change_4
    .byte 5, 13, 11, 1, 1, 0, 0, 0
    .word UnusedMapChanges11_change_5
    .byte 6, 12, 11, 1, 1, 0, 0, 0
    .word UnusedMapChanges11_change_6
    .byte 7, 11, 11, 1, 1, 0, 0, 0
    .word UnusedMapChanges11_change_7
    .byte 8, 14, 12, 1, 1, 0, 0, 0
    .word UnusedMapChanges11_change_8
    .byte 9, 13, 12, 1, 1, 0, 0, 0
    .word UnusedMapChanges11_change_9
    .byte 10, 12, 12, 1, 1, 0, 0, 0
    .word UnusedMapChanges11_change_10
    .byte 11, 11, 12, 1, 1, 0, 0, 0
    .word UnusedMapChanges11_change_11
    .byte 12, 14, 13, 1, 1, 0, 0, 0
    .word UnusedMapChanges11_change_12
    .byte 13, 13, 13, 1, 1, 0, 0, 0
    .word UnusedMapChanges11_change_13
    .byte 14, 12, 13, 1, 1, 0, 0, 0
    .word UnusedMapChanges11_change_14
    .byte 15, 11, 13, 1, 1, 0, 0, 0
    .word UnusedMapChanges11_change_15
    .byte 16, 14, 14, 1, 1, 0, 0, 0
    .word UnusedMapChanges11_change_16
    .byte 17, 13, 14, 1, 1, 0, 0, 0
    .word UnusedMapChanges11_change_17
    .byte 18, 12, 14, 1, 1, 0, 0, 0
    .word UnusedMapChanges11_change_18
    .byte 19, 11, 14, 1, 1, 0, 0, 0
    .word UnusedMapChanges11_change_19
    .word 0xff, 0, 0
