/* AUTO-GENERATED by scripts/generated_data/idspace.py -- DO NOT EDIT BY HAND.
 * Public typed ID / count / cap contract for Issue #10.
 * Regenerate with: python3 -m scripts.generated_data.idspace generate
 */
#ifndef GUARD_ID_SPACE_H
#define GUARD_ID_SPACE_H

#include "gba/types.h"

/* Compile-time assertion (C89-safe negative-array-size trick). */
#define ID_SPACE_STATIC_ASSERT(cond, tag) \
    typedef char id_space_static_assert_##tag[(cond) ? 1 : -1]

/* Character (unit logical ID) */
typedef u8 CharacterId;
typedef u16 CharacterCount;
#define CHARACTER_ID_STORAGE_BITS 8
#define CHARACTER_ID_SIGNED 0
#define CHARACTER_ID_SENTINEL 0
#define CHARACTER_ID_TECHNICAL_MAX 0xFF
#define CHARACTER_ID_CONFIGURED_CAP 0xFF

/* Class (job) ID */
typedef u8 ClassId;
typedef u8 ClassCount;
#define CLASS_ID_STORAGE_BITS 8
#define CLASS_ID_SIGNED 0
#define CLASS_ID_SENTINEL 0
#define CLASS_ID_TECHNICAL_MAX 0xFF
#define CLASS_ID_CONFIGURED_CAP 0xFF

/* Item ID */
typedef u8 ItemId;
typedef u16 ItemCount;
#define ITEM_ID_STORAGE_BITS 8
#define ITEM_ID_SIGNED 0
#define ITEM_ID_SENTINEL 0
#define ITEM_ID_TECHNICAL_MAX 0xFF
#ifndef FE8_ITEM_ID_CAP
#define FE8_ITEM_ID_CAP 0xCD
#endif
#define ITEM_ID_CONFIGURED_CAP FE8_ITEM_ID_CAP
#define ITEM_ID_EXPANSION_FIRST 0xCE

/* Chapter ID */
typedef s8 ChapterId;
typedef u8 ChapterCount;
#define CHAPTER_ID_STORAGE_BITS 7
#define CHAPTER_ID_SIGNED 1
#define CHAPTER_ID_SENTINEL -1
#define CHAPTER_ID_TECHNICAL_MAX 0x7F
#define CHAPTER_ID_CONFIGURED_CAP 0x7F

/* Unit (deployment) ID slot */
typedef u8 UnitId;
typedef u8 UnitCount;
#define UNIT_ID_STORAGE_BITS 8
#define UNIT_ID_SIGNED 0
#define UNIT_ID_SENTINEL 64
#define UNIT_ID_TECHNICAL_MAX 0x3F
#define UNIT_ID_CONFIGURED_CAP 0x3F

/* Event operand lane */
typedef u16 EventId;
typedef u16 EventCount;
#define EVENT_ID_STORAGE_BITS 16
#define EVENT_ID_SIGNED 0
#define EVENT_ID_TECHNICAL_MAX 0xFFFF
#define EVENT_ID_CONFIGURED_CAP 0xFF

/* Cap-fits-storage guarantees checked at compile time. */
ID_SPACE_STATIC_ASSERT(ITEM_ID_CONFIGURED_CAP <= ITEM_ID_TECHNICAL_MAX, item_cap_fits);
ID_SPACE_STATIC_ASSERT(ITEM_ID_TECHNICAL_MAX <= 0x3FFF, item_fits_save14);
ID_SPACE_STATIC_ASSERT(CLASS_ID_CONFIGURED_CAP <= 0xFF, class_cap_fits_jid8);
ID_SPACE_STATIC_ASSERT(CHARACTER_ID_CONFIGURED_CAP <= 0xFF, character_cap_fits_u8);
ID_SPACE_STATIC_ASSERT(CHAPTER_ID_CONFIGURED_CAP <= 0x7F, chapter_cap_fits_s8);
ID_SPACE_STATIC_ASSERT(UNIT_ID_CONFIGURED_CAP < 0x40, unit_cap_fits_faction);

#endif /* GUARD_ID_SPACE_H */
