#ifndef GUARD_MAPGEN_H
#define GUARD_MAPGEN_H

#include "global.h"

#if FE8_MAPGEN

/* Procedural chapter maps. Terrain is generated by randomly placing pre-made
 * tile "chunks" (src/mapgen_chunks_data.c, built from the .tmx library under
 * scripts/map_gen/chunks/) and filling whatever is left with plains. A base
 * tent per allegiance is placed independently, in opposite quadrants -- see
 * src/mapgen.c for the pipeline and for the determinism contract that governs
 * when each half of it runs. */

enum
{
    // Index into struct MapGenLayout::base, not a FACTION_ID -- see
    // sMapGenBaseOwner (src/mapgen.c) for the index -> FACTION_ID mapping.
    MAPGEN_BASE_PLAYER = 0,
    MAPGEN_BASE_ENEMY  = 1,

    MAPGEN_BASE_COUNT  = 2,
};

struct MapGenPoint
{
    s8 x;
    s8 y;
};

struct MapGenLayout
{
    struct MapGenPoint base[MAPGEN_BASE_COUNT];
};

/* Terrain half: a pure function of (chapterId, map size). Safe -- and
 * required -- to re-run on every map load, including save loads and
 * suspend/resume. */
void MapGen_GenerateTerrain(int chapterId);

/* Entity half: creates the tent traps. Must run exactly once per chapter, at
 * chapter start only, because traps are persisted in SRAM. */
void MapGen_PlaceBases(int chapterId);

/* Both halves agree on where the bases go by each calling this, rather than by
 * sharing state, so they can run at different times without coordination. */
void MapGen_GetLayout(int chapterId, struct MapGenLayout * out);

bool MapGen_IsEnabledForChapter(int chapterId);

/* Call once per VBlank, from as early in boot as possible (OnVBlank, src/bm.c)
 * -- feeds the free-running frame counter MapGen_SessionSeed() (src/mapgen.c)
 * uses as entropy. Deliberately separate from GetGameClock()/gGameClock: that
 * clock gets reset by SetGameTime() on paths that run before
 * MapGen_SessionSeed ever gets to read it (in particular WriteNewGameSave's
 * own SetGameTime(0), which fires before chapter 0's map -- and so this
 * generator -- ever loads), discarding exactly the boot-to-New-Game
 * menu-navigation entropy this needs. This counter is never reset by
 * anything. */
void MapGen_TickBootFrames(void);

#endif // FE8_MAPGEN

#endif // GUARD_MAPGEN_H
