#include "global.h"
#include "event.h"
#include "eventinfo.h"
#include "eventcall.h"
#include "eventscript.h"
#include "EAstdlib.h"
#include "chapterdata.h"
#include "constants/event-flags.h"
#include "bmunit.h"
#include "bmtrap.h"
#include "ending_credits.h"

/* Event scripts */
#include "events/vanilla/common-events.h"
#if !FE8_CUSTOM_CAMPAIGN
#include "events/vanilla/prologue-eventscript.h"
#include "events/vanilla/prologue-tutorials.h"
#include "events/vanilla/ch1-eventscript.h"
#include "events/vanilla/ch1-tutorials.h"
#endif
#include "events/vanilla/ch2-eventscript.h"
#include "events/vanilla/ch3-eventscript.h"
#include "events/vanilla/ch4-eventscript.h"
#include "events/vanilla/ch5-eventscript.h"
#include "events/vanilla/ch5x-eventscript.h"
#include "events/vanilla/ch6-eventscript.h"
#include "events/vanilla/ch7-eventscript.h"
#include "events/vanilla/ch8-eventscript.h"

#include "events/vanilla/ch9a-eventscript.h"
#include "events/vanilla/ch10a-eventscript.h"
#include "events/vanilla/ch11a-eventscript.h"
#include "events/vanilla/ch12a-eventscript.h"
#include "events/vanilla/ch13a-eventscript.h"
#include "events/vanilla/ch14a-eventscript.h"
#include "events/vanilla/ch15a-eventscript.h"
#include "events/vanilla/ch16a-eventscript.h"
#include "events/vanilla/ch17a-eventscript.h"
#include "events/vanilla/ch18a-eventscript.h"
#include "events/vanilla/ch19a-eventscript.h"
#include "events/vanilla/ch20a-eventscript.h"
#include "events/vanilla/ch21a-eventscript.h"
#include "events/vanilla/ch21xa-eventscript.h"

#include "events/vanilla/ch9b-eventscript.h"
#include "events/vanilla/ch10b-eventscript.h"
#include "events/vanilla/ch11b-eventscript.h"
#include "events/vanilla/ch12b-eventscript.h"
#include "events/vanilla/ch13b-eventscript.h"
#include "events/vanilla/ch14b-eventscript.h"
#include "events/vanilla/ch15b-eventscript.h"
#include "events/vanilla/ch16b-eventscript.h"
#include "events/vanilla/ch17b-eventscript.h"
#include "events/vanilla/ch18b-eventscript.h"
#include "events/vanilla/ch19b-eventscript.h"
#include "events/vanilla/ch20b-eventscript.h"
#include "events/vanilla/ch21b-eventscript.h"
#include "events/vanilla/ch21xb-eventscript.h"

#include "events/vanilla/tower-eventscript.h"
#include "events/vanilla/ruin-eventscript.h"

#include "events/vanilla/lordsplit-eventscript.h"
#include "events/vanilla/MelkaenCoast-eventscript.h"
#include "events/vanilla/unused-eventscript.h"
#include "events/vanilla/messed-eventscr.h"
