"""Config-gated CONTENT text for framework-authored item records (issue #6).

Why this module exists at all
-----------------------------
``texts/texts.txt`` is unconditional: every message in it is compressed into
ONE shared Huffman blob (``src/msg_data.c``), so appending a single
content-only message re-encodes the text of *every* build -- including a
default, feature-free ROM. An opt-in feature must not move the default ROM,
so a framework-authored record binds no message ID at all (see
``schema.py``'s POLICY note) and authors its original display text literally,
in the record, as ``authoringName``/``authoringDescription``/
``authoringUseDescription``.

What this module emits
----------------------
Only in the CONTENT PROFILE (``EXPANSION_STARTER_CONTENT=1``, which itself
requires an item cap that reaches the expansion IDs):

``items_expansion_content_text.h``
    A build-local C89 header holding the authored *names* as ordinary string
    literals in a typed, ``ItemId``-keyed table, plus the bound the runtime
    buffer is statically asserted against. ``src/expansion_starter_content.c``
    includes it and publishes the narrow public accessor
    ``ExpansionStarterContentItemName()``; ``src/bmitem.c``'s production
    ``GetItemName()`` reads that accessor -- and only under
    ``FE8_EXPANSION_STARTER_CONTENT``.

``items_expansion_content_text.json``
    An audit catalog of the same authored text, *including* the descriptions.
    The vanilla description/help UI is addressed exclusively by message ID,
    and a config-specific message table is out of scope for this example, so
    the descriptions are documentation/audit text only -- honestly not shown
    in-game. Nothing borrows a vanilla message to fake it.

In a default build this module emits NOTHING: no header, no catalog, no
string literal anywhere in the ROM. Both artifacts live under ``build/`` and
are never committed, and no generated C is ever hand-edited.
"""

from __future__ import annotations

import json
import os

from ..diagnostics import GeneratedDataError
from ..validators import extract_enum_constants
from .. import idspace
from .schema import (
    AUTHORING_NAME_MAX_CHARS,
    ITEMS_EXPANSION_HEADER,
    SCHEMA_NAME,
)

CONTENT_TEXT_HEADER_NAME = "items_expansion_content_text.h"
CONTENT_TEXT_CATALOG_NAME = "items_expansion_content_text.json"
CONTENT_TEXT_ARTIFACTS = (CONTENT_TEXT_HEADER_NAME, CONTENT_TEXT_CATALOG_NAME)

CATALOG_SCHEMA_ID = "fe8.items.content_text.v1"


def collect(records, expansion_header=ITEMS_EXPANSION_HEADER):
    """The authored content records, in ascending item-ID order.

    A record qualifies when it is an expansion overlay ID (so it can never
    be a vanilla item) AND it authored literal text. Returns a list of
    ``(item_symbol, item_value, record)`` triples."""
    if not os.path.exists(expansion_header):
        return []
    expansion_enum = extract_enum_constants(expansion_header, name_prefix="ITEM_")
    collected = []
    for record in records:
        entry = expansion_enum.get(record.item)
        if entry is None:
            continue
        if record.authoring_name is None:
            continue
        collected.append((record.item, entry[0], record))
    collected.sort(key=lambda triple: triple[1])
    return collected


def _c_string(text):
    """C89 string literal. The schema already rejects anything outside
    printable ASCII, so only the two structural characters can appear."""
    escaped = text.replace("\\", "\\\\").replace('"', '\\"')
    return '"{}"'.format(escaped)


def render_header(collected, source_path):
    """The build-local, content-profile-only authored-name table."""
    longest = max((len(r.authoring_name) for _, _, r in collected), default=0)
    lines = [
        "/* AUTO-GENERATED by scripts/generated_data -- DO NOT EDIT BY HAND.\n"
        " * Source: {source}\n"
        " * Regenerate with: EXPANSION_STARTER_CONTENT=1 python3 -m"
        " scripts.generated_data content-text\n"
        " *\n"
        " * Build-local CONTENT text (issue #6). Generated ONLY in the content\n"
        " * profile (EXPANSION_STARTER_CONTENT=1); a default build generates and\n"
        " * links no part of this file, so its ROM holds none of these strings.\n"
        " * The authored text lives in the item record itself -- no message is\n"
        " * added to the shared, Huffman-compressed table in texts/texts.txt.\n"
        " */\n".format(source=source_path),
        "\n",
        "#ifndef GUARD_ITEMS_EXPANSION_CONTENT_TEXT_H\n",
        "#define GUARD_ITEMS_EXPANSION_CONTENT_TEXT_H\n",
        "\n",
        "#include \"id_space.h\"\n",
        "#include \"constants/items_expansion.h\"\n",
        "\n",
        "/* Number of authored content records, and the longest authored name\n"
        " * (excluding the NUL). The consuming translation unit statically\n"
        " * asserts its own copy buffer against the capacity below. */\n",
        "#define EXPANSION_CONTENT_TEXT_COUNT {}\n".format(len(collected)),
        "#define EXPANSION_CONTENT_TEXT_NAME_CAPACITY {}\n".format(longest + 1),
        "\n",
        "struct ExpansionContentItemText\n",
        "{\n",
        "    ItemId item;\n",
        "    const char * name;\n",
        "};\n",
        "\n",
        "static const struct ExpansionContentItemText\n",
        "    sExpansionContentItemText[EXPANSION_CONTENT_TEXT_COUNT] =\n",
        "{\n",
    ]
    for symbol, _value, record in collected:
        lines.append("    {{ {}, {} }},\n".format(symbol, _c_string(record.authoring_name)))
    lines.append("};\n")
    lines.append("\n")
    lines.append("#endif /* GUARD_ITEMS_EXPANSION_CONTENT_TEXT_H */\n")
    return "".join(lines)


def render_catalog(collected, source_path):
    """The audit catalog: every authored string, including the descriptions
    the in-game help box cannot show (it is addressed by message ID, and this
    framework adds no messages)."""
    entries = []
    for symbol, value, record in collected:
        entries.append({
            "item": symbol,
            "itemId": value,
            "authoringName": record.authoring_name,
            "authoringDescription": record.authoring_description,
            "authoringUseDescription": record.authoring_use_description,
            "runtimeText": {
                "name": "generated content text table, read by the production "
                        "GetItemName() under FE8_EXPANSION_STARTER_CONTENT=1",
                "description": "not shown in game: the vanilla help/description "
                               "UI is addressed by message ID only, and no "
                               "message is added or reused",
            },
        })
    catalog = {
        "$schema": CATALOG_SCHEMA_ID,
        "source": source_path,
        "generatedBy": "scripts/generated_data/items/content_text.py",
        "profile": "EXPANSION_STARTER_CONTENT=1",
        "nameCapacity": max((len(r.authoring_name) for _, _, r in collected), default=0) + 1,
        "nameBound": AUTHORING_NAME_MAX_CHARS,
        "items": entries,
    }
    return json.dumps(catalog, indent=2, sort_keys=True) + "\n"


def resolve_content_flag(value=None, env=None):
    """Resolve the content profile switch from ``--content`` or the
    ``EXPANSION_STARTER_CONTENT`` environment variable (the same name
    config.mk/modern.mk use). Anything but 0/1 is a hard error."""
    if value is None:
        env = os.environ if env is None else env
        value = env.get("EXPANSION_STARTER_CONTENT", "0")
    text = str(value).strip() or "0"
    if text not in ("0", "1"):
        raise GeneratedDataError(
            "EXPANSION_STARTER_CONTENT must be 0 or 1, got '{}'".format(text),
            None, SCHEMA_NAME)
    return int(text)


def require_cap(cap):
    """The content profile is only meaningful at a cap that actually reaches
    the expansion IDs -- the same dependency config.mk, expansion_config.py
    and include/expansion_starter_content.h enforce."""
    if cap < idspace.ITEM_EXPANSION_FIRST:
        raise GeneratedDataError(
            "EXPANSION_STARTER_CONTENT=1 needs an item cap that reaches the "
            "expansion IDs: resolved cap 0x{:02X} < 0x{:02X} (build with "
            "FE8_ITEM_ID_CAP=0x{:02X} or higher)".format(
                cap, idspace.ITEM_EXPANSION_FIRST, idspace.ITEM_EXPANSION_FIRST),
            None, SCHEMA_NAME)
